### ISSUE TITLE
Ansible playbook脚本

### ISSUE THREAD

**Issue by fanhuadesenlinnn** [fanhuadesenlinnn/blog2#13]
### 配置yum源

```bash
ansible ceshi  -m yum_repository -a 'name=BASE \
description="software base" \
baseurl=http://11.33.18.197:4399 \
gpgcheck=no \
enabled=yes'
```

### 安装软件
```
cat install.yml

- hosts: 130,131,132,133
  tasks:
    - yum: pkg="iftop,tree,htop" state=present
```
